[build]
  publish = "."
  command = "npm install"

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/*.html"
  [headers.values]
    Content-Type = "text/html; charset=UTF-8"
    Content-Security-Policy = "script-src 'self' https://assets.calendly.com; object-src 'none'"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
